jobs:
- job: native_windows
  pool:
    vmImage: ubuntu-20.04
  container: mcr.microsoft.com/dotnet/sdk:8.0
  steps:
  - script: |
      mkdir -p $(System.DefaultWorkingDirectory)/nuget/
      dotnet pack AdkPlatformTools.csproj -c Release -o $(System.DefaultWorkingDirectory)/nuget/
    displayName: Pack AdkPlatformTools
    workingDirectory: AdkNuGetGenerator/AdkPlatformTools/
  - publish: $(System.DefaultWorkingDirectory)/nuget/
    artifact: WebApp