jobs:
- job: native_windows
  pool:
    vmImage: ubuntu-20.04
  container: mcr.microsoft.com/dotnet/sdk:6.0
  steps:
  - script: |
      dotnet run AdkNuGetGenerator.csproj -c Release
    displayName: Run AdkNuGetGenerator
    workingDirectory: AdkNuGetGenerator/AdkNuGetGenerator/
  - script: |
      mkdir -p nuget/
      cp AdkNuGetGenerator/AdkNuGetGenerator/*.nupkg ./nuget/
  - publish: $(System.DefaultWorkingDirectory)/nuget/
    artifact: WebApp
