jobs:
- job: native_windows
  pool:
    vmImage: ubuntu-20.04
  container: mcr.microsoft.com/dotnet/sdk:6.0
  steps:
  - script: |
      dotnet run AdkNuGetGenerator.csproj
    displayName: Run AdkNuGetGenerator
    workingDirectory: AdkNuGetGenerator/AdkNuGetGenerator/
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/runtimes'
      artifactName: runtimes
    displayName: Publish artifacts
